attack: ftrojan
attack_label_trans: all2one
attack_target: 0
pratio: 0.1
img_size: [32, 32, 3]

# FTrojan Params
yuv: True
channel_list: [1, 2]
window_size: 32
magnitude: 30.0
# Inject at high freq (31,31) and mid freq (15,15)
pos_list: [[31, 31], [15, 15]]

# Classifier Training
epochs: 100
batch_size: 128
lr: 0.01
lr_scheduler: MultiStepLR
# Steplr parameters to avoid AttributeError
steplr_milestones: [50, 75]
steplr_gamma: 0.1

model: preactresnet18
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005
frequency_save: 0
device: cuda:0
dataset_path: "./data/cifar10"